version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount the entire project directory
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/movie_reviews
    command: >
      sh -c "aerich upgrade &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: unless-stopped  # Add restart policy

  db:
    image: registry.hub.docker.com/library/postgres:15.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movie_reviews
    ports:
      - "5432:5432"
    restart: unless-stopped  # Add restart policy

volumes:
  postgres_data: 